version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 096085967110.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo CodeBuild URL $CODEBUILD_BUILD_URL
      - echo Building the $SERVER_REPO_NAME Docker image...
      - docker build -t trainee_backend . --target production
  post_build:
    commands:
      - echo Build completed on `date -Ins -u`
      - echo Pushing built Docker images...
      - docker tag trainee_backend:latest 096085967110.dkr.ecr.us-east-2.amazonaws.com/trainee_backend:latest
      - docker push 096085967110.dkr.ecr.us-east-2.amazonaws.com/trainee_backend:latest
