# Generated by Django 3.2.4 on 2021-07-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='ratemodel',
            options={'ordering': ('-created',)},
        ),
    ]
